### ISSUE TITLE
NotImplementedError: CUDA_HOME is None. Please set environment variable CUDA_HOME.

### ISSUE THREAD

**Issue by hhliu924** [slonetime/EBSeg#4]
torch.cuda.is_available() is True.How can I solve this problem?

**Comment by slonetime** [comment]
This error indicates that the environment variable CUDA_HOME is not set, which is required for PyTorch to locate your CUDA installation. You can solve this problem by setting the the environment variable CUDA_HOME in your ~/.bashrc  file.
