### ISSUE TITLE
Visualization on the trained models. 

### ISSUE THREAD

**Issue by ZhengyuXia** [slonetime/EBSeg#6]
Hi, thanks for the work. I would like to know how we can visualize the work as shown in the paper. Are there any available codes or reference links if you can share with us. Thank you.

**Comment by slonetime** [comment]
Hello, regarding obtaining the visualization results, you can refer to the code in [SAN](https://github.com/MendelXu/SAN/blob/81a9a2bd79d433292d46cfa0597caea5005e0116/predict.py#L148).

**Comment by ZhengyuXia** [comment]
Thanks for sharing the reference codes. Although it does not work for me, the other one "[visualize_json_results.py](https://github.com/MendelXu/SAN/blob/main/visualize_json_results.py)" works like a charm.
