### ISSUE TITLE
About the training cost

### ISSUE THREAD

**Issue by shuo1874** [slonetime/EBSeg#7]
Hello Author, thank you for your work. May I ask what kind of graphics card you used to train the model, how much VRAM it consumed, and how much training time was required?

**Comment by slonetime** [comment]
Thanks for the question, we use A100 80G GPUs for our training, two GPUs for EBSeg-base, four GPUs for EBSeg-large, and it takes about two days to train our models. Both the base model and the large model consume about 50G memory per GPU card. However, the computational resources consumed may vary in different environments.

**Comment by shuo1874** [comment]
OK. Thanks for your reply.
